[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

# Add these environment variables in your Netlify dashboard:
# NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"
# SITE_URL = "https://your-site-name.netlify.app" 